### ISSUE TITLE
Rails Assets component error 

### ISSUE THREAD

**Issue by tomkuk** [marianoguerra/json.human.js#36]
Hi @marianoguerra,

I tried to get json.human.js working with rails-assets but it fails with the following message.

> json-human has no versions defined. Please create an issue in component's repository.

The problem is the lack of version tag. Could you please create a tag with current revision of the package using semver format? It could be 0.0.1, or anything you suggest.

Here is the component import page to check it working: https://rails-assets.org/components/new

**Comment by marianoguerra** [comment]
this should do it https://github.com/marianoguerra/json.human.js/releases/tag/0.1

reopen if not

**Comment by tomkuk** [comment]
@marianoguerra thanks for the quick reaction, although I got still the same message. I'm not sure if version 0.1 is proper [semver](http://semver.org/) format

**Comment by marianoguerra** [comment]
try this one https://github.com/marianoguerra/json.human.js/releases/tag/0.1.1

**Comment by tomkuk** [comment]
it works, thanks!
